services:
  otelcol:
    image: otel/opentelemetry-collector:latest
    ports:
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    command: ['--config', '/etc/otelcol-config.yaml']

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'