services:
  otelcol:
    image: otel/opentelemetry-collector:latest
    ports:
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    command: ['--config', '/etc/otelcol-config.yaml']

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '5778:5778'
      - '9411:9411'